# Generated by Django 2.2.3 on 2019-07-23 08:48

from django.db import migrations, models
import kayit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kayitislemi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(help_text='Adınızı giriniz.', max_length=100, null=True, verbose_name='Ad :')),
                ('soyad', models.CharField(help_text='Soyadınızı giriniz.', max_length=100, null=True, verbose_name='Soyad :')),
                ('adres', models.TextField(help_text='Adresinizi giriniz.', max_length=1000, null=True, verbose_name='Adres :')),
                ('dogum_tarihi', models.CharField(help_text='Doğum tarihinizi giriniz.', max_length=100, null=True, verbose_name='Dogum tarihi :')),
                ('veli1', models.CharField(help_text='1. velinizi giriniz.', max_length=100, null=True, verbose_name='1. Veli :')),
                ('veli2', models.CharField(help_text='2. velinizi giriniz.', max_length=100, null=True, verbose_name='2. Veli :')),
                ('email', models.EmailField(help_text='E-postanızı giriniz.', max_length=50, null=True, verbose_name='E-posta :')),
                ('hobi', models.TextField(help_text='Hobilerinizi giriniz.', max_length=1000, null=True, verbose_name='Hobi :')),
                ('telefon', models.CharField(help_text='Telefonunuzu giriniz.', max_length=100, null=True, verbose_name='Telefon :')),
                ('image', models.ImageField(blank=True, max_length=150, null=True, upload_to=kayit.models._handle_file_upload, verbose_name='Fotograf :')),
                ('odeme', models.IntegerField(choices=[(1, '---'), (2, 'Peşin = 54.000 TL'), (3, '3 Taksit = 56.000 TL'), (4, '6 Taksit = 60.000 TL'), (5, '9 Taksit = 65.000 TL')], default=1, null=True, verbose_name='ödeme İşlemi :')),
            ],
            options={
                'verbose_name_plural': 'Öğrenci Kayıtları',
                'ordering': ['id'],
            },
        ),
    ]
