# Generated by Django 2.2.3 on 2019-07-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kayit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='başlık bilgisi', max_length=100, null=True, verbose_name='baslık')),
                ('content', models.TextField(max_length=1000, null=True, verbose_name='içerik')),
                ('creted_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
