# Generated by Django 2.2.3 on 2019-07-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayıt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kayıtislemi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(help_text='Adınızı giriniz.', max_length=100, null=True, verbose_name='Ad :')),
                ('soyad', models.CharField(help_text='Soyadınızı giriniz.', max_length=100, null=True, verbose_name='Soyad :')),
                ('adres', models.TextField(help_text='Adresinizi giriniz.', max_length=1000, null=True, verbose_name='Adres :')),
                ('dogum_tarihi', models.TimeField(help_text='Dogum tarihinizi giriniz.', verbose_name='Dogum tarihi:')),
                ('veli1', models.CharField(help_text='1. velinizi giriniz.', max_length=100, null=True, verbose_name='1. Veli :')),
                ('veli2', models.CharField(help_text='2. velinizi giriniz.', max_length=100, null=True, verbose_name='2. Veli :')),
                ('email', models.EmailField(help_text='E-postanızı giriniz.', max_length=50, null=True, verbose_name='E-posta :')),
                ('hobi', models.TextField(help_text='Hobilerinizi giriniz.', max_length=1000, null=True, verbose_name='Hobi :')),
                ('telefon', models.CharField(help_text='Telefonunuzu giriniz.', max_length=100, null=True, verbose_name='Telefon :')),
                ('fotograf', models.ImageField(help_text=150, upload_to='', verbose_name='fotograf :', width_field=150)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'öğrenci kayıtları',
            },
        ),
        migrations.DeleteModel(
            name='Kayit',
        ),
    ]
