# Generated by Django 2.2.3 on 2019-07-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayıt', '0002_auto_20190717_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kayıtislemi',
            name='dogum_tarihi',
        ),
    ]
