# Generated by Django 2.2.3 on 2019-07-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayıt', '0003_remove_kayıtislemi_dogum_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayıtislemi',
            name='dogum_tarihi',
            field=models.CharField(help_text='Doğum tarihinizi giriniz.', max_length=100, null=True, verbose_name='Dogum tarihi :'),
        ),
    ]
