# Generated by Django 2.2.3 on 2019-07-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayıt', '0004_kayıtislemi_dogum_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayıtislemi',
            name='fotograf',
            field=models.ImageField(blank=True, upload_to='', verbose_name='fotograf :'),
        ),
    ]
