# Generated by Django 2.2.3 on 2019-07-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayıt', '0005_auto_20190718_0817'),
    ]

    operations = [

        migrations.AddField(
            model_name='kayıtislemi',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_image', verbose_name='fotograf'),
        ),
    ]
