# Generated by Django 2.2.3 on 2019-07-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayıt', '0006_auto_20190718_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kayıtislemi',
            name='fotograf',
        ),
        migrations.AlterField(
            model_name='kayıtislemi',
            name='image',
            field=models.ImageField(blank=True, null=True, verbose_name='fotograf'),
        ),
    ]
