# Generated by Django 2.2.3 on 2019-07-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayıt', '0010_auto_20190718_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayıtislemi',
            name='odeme',
            field=models.IntegerField(choices=[(1, '---'), (2, 'Peşin = 54.000 TL'), (3, '3 Taksit = 56.000 TL'), (4, '6 Taksit = 60.000 TL'), (5, '9 Taksit = 65.000 TL')], default=1, max_length=100, null=True, verbose_name='ödeme İşlemi :'),
        ),
    ]
