# Generated by Django 2.2.3 on 2019-07-18 11:35

from django.db import migrations, models
import kayıt.models


class Migration(migrations.Migration):

    dependencies = [
        ('kayıt', '0011_auto_20190718_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayıtislemi',
            name='image',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to=kayıt.models._handle_file_upload, verbose_name='Fotograf :'),
        ),
    ]
